sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t username/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true username/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'my-docker'
  env: 'Mydocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-633071163946'
  bucket_path: 'my-docker'
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
